# docker compose file
version: '3'
volumes:
    node_modules:
services:
    gatsby:
        container_name: gatsby
        build:
          context: .
        user: 'node'
        working_dir: /home/node/app
        environment:
          - NODE_ENV=development
        volumes:
          - ./:/home/node/app
          # mount empty node_modules exclude the node_modules on host system from mounting into the container
          - node_modules:/home/node/app/node_modules
        ports:
          - '8000:8000'
        command: 'yarn start'
    mongodb:
        image: mongo:latest
        container_name: strapi-mongo
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_DATABASE: strapi
    strapi:
        image: strapi/strapi
        container_name: strapi
        depends_on:
            - mongodb
        ports:
            - "1337:1337"
        environment:
            APP_NAME: strapi-app
            DATABASE_CLIENT: mongo
            DATABASE_HOST: strapi-mongo
            DATABASE_PORT: 27017
            DATABASE_NAME: strapi
